### PR TITLE
Disable caching of time zones

### PR DESCRIPTION
**Pull request by elonazoulay**
Remove creation of CachedDateTimeZone for non fixed time zones.
This reduces the excessive number of CachedDateTimeZone$Info instances.

### CODE REVIEW

**Comment by elonazoulay** [comment]
This is related to https://github.com/prestodb/presto/issues/12235

**Comment by dain** [comment]
@elonazoulay Is the assumption that caching is not needed because the underlying JDK `ZoneRules` caches already?

**Review by electrum — APPROVED** [review]
Please update the commit title and description
```
Remove unnecessary caching of time zones

The underlying java.time ZoneRules already does caching.

**Comment by elonazoulay** [comment]
Thanks! Updated the commit message.

**Pull request merged**
